### ISSUE TITLE
feat: Change Font: Fonts are too hard to read when using this font in paragraphs or a group of sentences

### ISSUE THREAD

**Issue by dschinkel** [gregorriegler/mob-programming-rpg#4]
I get it, it's a game theme.

The Font is fine for buttons and such, but don't use this font for reading paragraphs / bunch of sentences.  My eyes get cross eyed when I read the settings and other pages like this.  Can you figure something out for those kinds of pages, I can't read this.

![Screenshot 2023-02-21 at 8 26 02 PM Large](https://user-images.githubusercontent.com/338798/220508088-8d9a4ec4-a1cd-40e0-9cb0-e57adc1ec406.jpeg)

**Comment by gregorriegler** [comment]
Thanks @dschinkel , good point.
We'll definitely work on improving this.

**Comment by gregorriegler** [comment]
We improved the font today, do you like it better now?

**Comment by MichaelRWolf** [comment]
I do like it.   The old font was sooo hard to read.  And it reminded me of a video game from the 1970's.  Nice nostalgia, but there's a reason we have newer fonts -- we have better screens, and newer fonts are more readable.  Thanks for the change!

**Comment by MichaelRWolf** [comment]
Here are the fonts that ChatGPT suggested
- https://fonts.google.com/specimen/Roboto
- https://fonts.google.com/specimen/Open+Sans
- https://fonts.google.com/specimen/Lato
- https://fonts.google.com/specimen/Montserrat
- https://fonts.google.com/specimen/Play
- https://fonts.google.com/specimen/VT323

I think we choose
- https://fonts.google.com/specimen/Roboto+Mono


Here is the [ChatGPT session](https://chat.openai.com/chat/123fbb6a-d3b9-4c66-9dbf-6caf0e9459a5)

michaelrwolf@att.net
I am creating a game that uses a google font called "Press Start to P".  It is ugly.  What is a better font for a game that's played in a browser tab?

When choosing a font for a game that's played in a browser tab, you should consider several factors such as legibility, readability, and the overall aesthetic of your game. Some good options for fonts that are easy to read and look great on a browser tab are:

Roboto: This font was designed by Google and is widely used across the web. It's clean, modern, and easy to read, making it a great choice for a game.

Open Sans: This font is also designed by Google and is similar to Roboto in its clean and modern look. It's a versatile font that can work well for both headings and body text.

Lato: This font has a more unique look than Roboto and Open Sans but still offers excellent legibility. It's a great choice if you want to add a bit of personality to your game.

Montserrat: This font has a more condensed look, making it a good choice if you have limited space on your browser tab. It's still very legible and looks great in both headings and body text.

Play: This font is specifically designed for games and has a playful, retro look that could work well depending on the style of your game.

Ultimately, the font you choose will depend on your game's overall aesthetic and the message you want to convey to your players. It's a good idea to experiment with different fonts and see which one works best for your specific game.




michaelrwolf@att.net
What is closer to the look and feel of the original font?

If you're looking for a font that's similar in look and feel to "Press Start to P" but more aesthetically pleasing, you may want to consider "VT323". It's a free Google font that has a retro, pixelated appearance similar to "Press Start to P," but with more refined letterforms and improved legibility. Another option that has a similar feel is "Pixel Emulator," which is a paid font available on websites like MyFonts.com. However, it's worth noting that both of these fonts may not be as legible as some of the other options I mentioned earlier, so you'll want to test them out to see how they look in the context of your game
